# WordPress Configuration
---
- name: Clone latest Wordpress
  ansible.builtin.git:
    repo: https://github.com/ansible/ansible-examples.git
    dest: "/var/www/{{ http_host }}"
    version: master

- name: Set up wp-config
  template:
    src: "../files/wp-config.php.j2"
    dest: "/var/www/{{ http_host }}/wordpress/wp-config.php"

- name: Set ownership
  file:
    path: "/var/www/html"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
... 


