# WordPress Configuration
---
- name: Download and unpack latest WordPress
  unarchive:
    src: "https://wordpress.org/latest.tar.gz"
    dest: "/var/www/{{ http_host }}"
    remote_src: yes
    creates: "/var/www/{{ http_host }}/wordpress"

- name: Set up wp-config
  template:
    src: "../files/wp-config.php.j2"
    dest: "/var/www/{{ http_host }}/wordpress/wp-config.php"

- name: Set ownership
  file:
    path: "/var/www/html"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
... 


